import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";

interface Section {
  title: string;
  description: string;
  slug: string;
}
const Home = ({sections}: {sections: Section[]}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Expray producciones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{sections.map((e) => (
        <div>
        <h2>{e.title}</h2>
        <p>{e.description}</p>
        </div>
      ))}</main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:1337/sections/");
  const sections = res.data;
  return {
    props: {
      sections,
    },
  };
};
export default Home;
